//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiNaturguiden.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsPicture
    {
        public int News { get; set; }
        public int Picture { get; set; }
    
        public virtual News News1 { get; set; }
    }
}
